CREATE database WALMART;
-- Set Walmart as default schema
-- Create table sales
CREATE TABLE SALES(
	invoice_id varchar(30) PRIMARY KEY,
	branch varchar(5) NOT NULL,
	city varchar(30) NOT NULL,
	customer_type varchar(30) NOT NULL,
	gender varchar(10) NOT NULL,
	product_line varchar(100) NOT NULL,
	unit_price decimal(10,2) NOT NULL,
	quantity int NOT NULL,
	VAT float(6,4) NOT NULL,
	total decimal(12,4) NOT NULL,
	date datetime NOT NULL,
	time TIME NOT NULL,
	payment_method varchar(15) NOT NULL,
	cogs DECIMAL(10,2) NOT NULL,
	gross_margin_percentage FLOAT(11,9),
	gross_income DECIMAL(12,4),
	rating FLOAT(2,1)
);
-- Import dataset 

-- What is the total sales amount for each branch?
SELECT 
	branch, 
    SUM(total) AS total_sales
FROM sales
GROUP BY branch;

-- How do sales trends vary month by month?
SELECT 
	DATE_FORMAT(date, '%Y-%m') AS month, 
    SUM(total) AS monthly_sales
FROM sales
GROUP BY DATE_FORMAT(date, '%Y-%m')
ORDER BY month;

-- What is the average unit price for each product line?
SELECT 
	product_line, 
    AVG(unit_price) AS average_unit_price
FROM sales
GROUP BY product_line;

-- How are sales distributed among different customer types?
SELECT 
	customer_type, 
    COUNT(*) AS number_of_sales, 
    SUM(total) AS total_sales
FROM sales
GROUP BY customer_type;

-- What are the total sales and average purchase amount for each gender?
SELECT 
	gender, 
    SUM(total) AS total_sales, 
    AVG(total) AS average_purchase
FROM sales
GROUP BY gender;

-- Which cities have the highest total sales?
SELECT 
	city, 
    SUM(total) AS total_sales
FROM sales
GROUP BY city
ORDER BY total_sales DESC;

-- During which hours of the day are most sales made?
SELECT 
	HOUR(time) AS hour_of_day, 
	COUNT(*) AS number_of_sales, 
	SUM(total) AS total_sales
FROM sales
GROUP BY hour_of_day
ORDER BY number_of_sales DESC;

-- What is the average customer rating for each product line?
SELECT 
	product_line, 
    ROUND(AVG(rating), 2) AS average_rating
FROM sales
GROUP BY product_line;

-- How much gross income is generated by each branch?
SELECT 
	branch, 
    SUM(gross_income) AS total_gross_income
FROM sales
GROUP BY branch;

-- What is the gross margin percentage and total gross income for each branch?
SELECT 
	branch, 
    AVG(gross_margin_percentage) AS average_gross_margin, 
    SUM(gross_income) AS total_gross_income
FROM sales
GROUP BY branch;

-- How have sales performed over time (daily basis)?
SELECT 
	date, 
    SUM(total) AS daily_sales
FROM sales
GROUP BY date
ORDER BY date;

-- How are different payment methods used by customers?
SELECT 
	payment_method, 
    COUNT(*) AS number_of_transactions, 
    SUM(total) AS total_amount
FROM sales
GROUP BY payment_method;

-- What is the cost of goods sold (COGS) for each product line?
SELECT 
	product_line, 
    SUM(cogs) AS total_cogs
FROM sales
GROUP BY product_line;

-- What is the total VAT collected for each branch?
SELECT 
	branch, 
    SUM(VAT) AS total_vat
FROM sales
GROUP BY branch;

-- What is the total quantity of products sold for each product line?
SELECT 
	product_line, 
    SUM(quantity) AS total_quantity_sold
FROM sales
GROUP BY product_line;














	